/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.t3b.venta.gui.busqueda;

import com.org.t3b.core.gui.VPantalla;
import com.org.t3b.venta.controller.Controlador;
import com.org.t3b.venta.utils.BKeyListener;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author roberto
 */
public class VBusqueda extends VPantalla implements KeyListener{

    /**
     * Creates new form VBusqueda
     */
    public VBusqueda() {
        initComponents();
    }
    
    public VBusqueda(Controlador c,HashMap<String, Object> p) {
        super(c, p);
        initComponents();
        iniciaListener();
    }
    
    
    private void iniciaListener(){
        this.tDescripcion.addKeyListener(this);
        this.tProductos.addKeyListener(new BKeyListener(this));
        this.bF1.addKeyListener(this);
        this.bEsc.addKeyListener(this);
        this.addKeyListener(this);
        
    }

    public JButton getbEsc() {
        return bEsc;
    }

    public void setbEsc(JButton bEsc) {
        this.bEsc = bEsc;
    }

    public JButton getbF1() {
        return bF1;
    }

    public void setbF1(JButton bF1) {
        this.bF1 = bF1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JPanel getjPanel6() {
        return jPanel6;
    }

    public void setjPanel6(JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    public JPanel getjPanel7() {
        return jPanel7;
    }

    public void setjPanel7(JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField gettDescripcion() {
        return tDescripcion;
    }

    public void settDescripcion(JTextField tDescripcion) {
        this.tDescripcion = tDescripcion;
    }

    public JTable gettProductos() {
        return tProductos;
    }

    public void settProductos(JTable tProductos) {
        this.tProductos = tProductos;
    }
    
    private void buscaProducto(){
        String [] parametros = new String[1];
        Controlador controlador = (Controlador)this.getControlador();
        parametros[0]=this.tDescripcion.getText();
        controlador.ejecutaAccion("Busqueda","busquedaProducto", parametros);
    }
    
    
    public void salir(){
        Controlador controlador = (Controlador)this.getControlador();
        controlador.ejecutaAccion("Busqueda","salirBusqueda");
    }

    public void f1Aceptar(){
        String [] parametros = new String[30];
        Controlador controlador = (Controlador)this.getControlador();
        int itemSeleccionado=tProductos.getSelectedRow();
        if(itemSeleccionado>=0) {
            
            if(controlador.mensajeVistaDecision(this, "¿ Desea Agregar el Articulo ? ","Agregar Articulo")==0){
            
                DefaultTableModel model = (DefaultTableModel) tProductos.getModel();
                parametros[0]=(String)model.getValueAt(itemSeleccionado,1);
                parametros[1]="1";
                controlador.ejecutaAccion("Busqueda","agregarBusqueda", parametros);
            
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tDescripcion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bF1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        bEsc = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Articulo"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 60));
        jPanel2.setPreferredSize(new java.awt.Dimension(677, 60));

        jLabel1.setText("Buscar por: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 350));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 350));
        jPanel3.setPreferredSize(new java.awt.Dimension(677, 350));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Codigo Barras", "Producto", "Ticket", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tProductos);
        if (tProductos.getColumnModel().getColumnCount() > 0) {
            tProductos.getColumnModel().getColumn(0).setResizable(false);
            tProductos.getColumnModel().getColumn(0).setPreferredWidth(50);
            tProductos.getColumnModel().getColumn(1).setResizable(false);
            tProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
            tProductos.getColumnModel().getColumn(2).setResizable(false);
            tProductos.getColumnModel().getColumn(2).setPreferredWidth(250);
            tProductos.getColumnModel().getColumn(3).setResizable(false);
            tProductos.getColumnModel().getColumn(3).setPreferredWidth(120);
            tProductos.getColumnModel().getColumn(4).setResizable(false);
            tProductos.getColumnModel().getColumn(4).setPreferredWidth(120);
        }

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 60));
        jPanel4.setPreferredSize(new java.awt.Dimension(677, 60));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setMaximumSize(new java.awt.Dimension(338, 32767));
        jPanel6.setMinimumSize(new java.awt.Dimension(338, 100));
        jPanel6.setLayout(new java.awt.BorderLayout());

        bF1.setText("F1 | Aceptar");
        bF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bF1ActionPerformed(evt);
            }
        });
        jPanel6.add(bF1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6);

        jPanel7.setMaximumSize(new java.awt.Dimension(339, 32767));
        jPanel7.setMinimumSize(new java.awt.Dimension(339, 100));
        jPanel7.setLayout(new java.awt.BorderLayout());

        bEsc.setText("Esc | Cancelar");
        bEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEscActionPerformed(evt);
            }
        });
        jPanel7.add(bEsc, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEscActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_bEscActionPerformed

    private void bF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bF1ActionPerformed
        // TODO add your handling code here:
        f1Aceptar();
    }//GEN-LAST:event_bF1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEsc;
    private javax.swing.JButton bF1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tDescripcion;
    private javax.swing.JTable tProductos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if ((e.getKeyCode() != KeyEvent.VK_BACK_SPACE) || (e.getKeyCode() != 40)|| (e.getKeyCode() != 38)) {
            buscaProducto();
        }
        
        switch(e.getKeyCode()){
            
            case KeyEvent.VK_ESCAPE: salir();break;
            case KeyEvent.VK_F1: f1Aceptar();break;
            
        }
        
        
    }

    @Override
    public void keyReleased(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
