/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.t3b.epagos.gui.main;

import java.util.HashMap;

import com.org.t3b.epagos.controller.Controlador;
import com.org.t3b.epagos.controller.ControladorTA;

/**
 *
 * @author roberto
 */
public class TA extends javax.swing.JInternalFrame {

    private ControladorTA controller;
    /**
     * Creates new form TA
     */
    public TA() {
        initComponents();
    }
    
    public TA(ControladorTA c) {
        initComponents();
        this.controller=c;
    }

    private HashMap<String, Object> regresaParametros(String marca){
       HashMap<String, Object> p = new HashMap<>();
       
       p.put("marca",marca);
       p.put("ventana", this);
       
       return p;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bMovistar = new javax.swing.JButton();
        bTelcel = new javax.swing.JButton();
        bUnefon = new javax.swing.JButton();
        bATT = new javax.swing.JButton();
        lMensaje = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        tVentaTA = new javax.swing.JToolBar();
        lTienda = new javax.swing.JLabel();
        lCaja = new javax.swing.JLabel();
        lInternet = new javax.swing.JLabel();
        lFecha = new javax.swing.JLabel();
        lVersion = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecciona Compañia"));

        bMovistar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bMovistar.setText("2 | MoviStar");
        bMovistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMovistarActionPerformed(evt);
            }
        });

        bTelcel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bTelcel.setText("1 | Telcel");
        bTelcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTelcelActionPerformed(evt);
            }
        });

        bUnefon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bUnefon.setText("3 | Unefon");
        bUnefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUnefonActionPerformed(evt);
            }
        });

        bATT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bATT.setText("4 | AT&T");
        bATT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bATTActionPerformed(evt);
            }
        });

        lMensaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lMensaje.setText("Siguiente Paso Selccione el producto >>");

        bCancelar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        bCancelar.setText("Esc | Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTelcel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUnefon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bATT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMovistar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lMensaje)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMovistar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTelcel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bUnefon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bATT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(bCancelar)
                .addGap(7, 7, 7))
        );

        tVentaTA.setRollover(true);

        lTienda.setText("Tienda: 1     ");
        tVentaTA.add(lTienda);

        lCaja.setText("Caja: 01    ");
        tVentaTA.add(lCaja);

        lInternet.setText("Internet: Si   ");
        tVentaTA.add(lInternet);

        lFecha.setText("Fecha: 2020-05-09   ");
        tVentaTA.add(lFecha);

        lVersion.setText("Version: 1.0");
        tVentaTA.add(lVersion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tVentaTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tVentaTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUnefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUnefonActionPerformed
        // TODO add your handling code here:
        this.controller.ejecutaAccion("consultaProductos", this.regresaParametros("unefon"));
    }//GEN-LAST:event_bUnefonActionPerformed

    private void bATTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bATTActionPerformed
        // TODO add your handling code here:
        this.controller.ejecutaAccion("consultaProductos",this.regresaParametros("att"));
    }//GEN-LAST:event_bATTActionPerformed

    private void bTelcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTelcelActionPerformed
        // TODO add your handling code here:
        this.controller.ejecutaAccion("consultaProductos", this.regresaParametros("telcel"));
    }//GEN-LAST:event_bTelcelActionPerformed

    private void bMovistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMovistarActionPerformed
        // TODO add your handling code here:
        this.controller.ejecutaAccion("consultaProductos", this.regresaParametros("movistar"));
    }//GEN-LAST:event_bMovistarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bATT;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bMovistar;
    private javax.swing.JButton bTelcel;
    private javax.swing.JButton bUnefon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lCaja;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lInternet;
    private javax.swing.JLabel lMensaje;
    private javax.swing.JLabel lTienda;
    private javax.swing.JLabel lVersion;
    private javax.swing.JToolBar tVentaTA;
    // End of variables declaration//GEN-END:variables
}
