/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.t3b.pv.t3bcore.gui;

import com.t3b.pv.t3bcore.controller.ControladorG;
import java.util.HashMap;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author roberto
 */
public class VPantalla extends javax.swing.JInternalFrame{

    /**
	 * 
	 */
	private static final long serialVersionUID = -3121574328715036369L;
	private ControladorG controlador;
    private HashMap<String, Object> parametros;
    
    /**
     * Creates new form VPantalla
     */
    public VPantalla() {
        //initComponents();
    }
    
    public VPantalla(ControladorG c,HashMap<String, Object> p) {
        this.controlador=c;
        this.parametros=p;
        //initComponents();
    }

    public ControladorG getControlador() {
        return controlador;
    }

    public void setControlador(ControladorG controlador) {
        this.controlador = controlador;
    }

    public HashMap<String, Object> getParametros() {
        return parametros;
    }

    public void setParametros(HashMap<String, Object> parametros) {
        this.parametros = parametros;
    }

    public int mensajeVistaDecision(JInternalFrame v,String mensaje,String titulo){
        int regreso=JOptionPane.showConfirmDialog(v,mensaje,titulo,JOptionPane.ERROR_MESSAGE);
        System.out.println("Confirmacion: "+regreso);
        return regreso;
    }
    
    
    public void mensajeVista(JInternalFrame v,String mensaje,String titulo){

        JOptionPane.showMessageDialog(v,mensaje,titulo,JOptionPane.ERROR_MESSAGE);
    }
    
    
    public void mensajeVistaUnico(JInternalFrame v,String mensaje,String titulo){
       JOptionPane.showMessageDialog(v,mensaje,titulo,JOptionPane.ERROR_MESSAGE);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unused")
	private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}
